p2/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('', views.bienvenida, name="bienvenida"),
    path('listacursos/', views.listacursos, name="listacursos"),
    path('crear-curso/', views.crearCurso, name="crear-curso"),
    path('actualizar-curso/<str:pk>/', views.actualizarCurso, name="actualizar-curso"),
    path('eliminar-curso/<str:pk>/', views.eliminarCurso, name="eliminar-curso"),
    path('curso/<str:pk>/', views.curso, name="curso"),
    path('crear-estudiante/<str:pk>/', views.crearEstudiante, name="crear-estudiante"),
    path('actualizar-estudiante/<str:pk>/', views.actualizarEstudiante, name="actualizar-estudiante"),
    path('eliminar-estudiante/<str:pk>/', views.eliminarEstudiante, name="eliminar-estudiante"),
    path('listapruebas/', views.listapruebas, name="listapruebas"),
    path('crear-prueba/', views.crearPrueba, name="crear-prueba"),
    path('actualizar-prueba/<str:pk>/', views.actualizarPrueba, name="actualizar-prueba"),
    path('eliminar-prueba/<str:pk>/', views.eliminarPrueba, name="eliminar-prueba"),
    path('prueba/<str:pk>/', views.prueba, name="prueba"),
    path('crear-preguntas/<str:pk>/', views.crearPreguntas, name="crear-preguntas"),
    path('actualizar-preguntas/<str:pk>/', views.actualizarPreguntas, name="actualizar-preguntas"),
    path('eliminar-preguntas/<str:pk>/', views.eliminarPreguntas, name="eliminar-preguntas"),
    path('pregunta/<str:pk>/', views.pregunta, name="pregunta"),
    path('relacionar-preguntas/<str:pk>/', views.relacionarPreguntas, name="relacionar-preguntas"),
    path('eliminar-relacion-preguntas/<str:pk>/', views.eliminarRelacionPreguntas, name="eliminar-relacion-preguntas"),
    path('listatemas/', views.listatemas, name="listatemas"),
    path('crear-tema/', views.crearTema, name="crear-tema"),
    path('actualizar-tema/<str:pk>/', views.actualizarTema, name="actualizar-tema"),
    path('eliminar-tema/<str:pk>/', views.eliminarTema, name="eliminar-tema"),
]

p2/p2/urls.py
from django.contrib import admin
from django.urls import path, include 
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('__debug__', include(debug_toolbar.urls)),
]

p2/base/models.py
from django.db import models
from django.contrib.auth.models import User

class Prueba(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pruebas')
    nombre_prueba = models.CharField('Nombre Prueba', max_length=100)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_prueba

class Tema(models.Model):
    nombre_tema = models.CharField('Nombre Tema', max_length=100)

    def __str__(self):
        return str(self.id) + '-' + self.nombre_tema

class Preguntas(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prueba = models.ForeignKey(Prueba, on_delete=models.CASCADE)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)

    pregunta = models.CharField('Pregunta', max_length=100)
 
    def nombreprueba(self):
        return self.prueba.nombre_prueba

    def nombretema(self):
        return self.tema.nombre_tema

    def __str__(self):
        return str(self.id) + '-' + self.pregunta

class Curso(models.Model):
    nombre_curso = models.CharField('Nombre del Curso', max_length=100)

    def __str__(self):
        return self.nombre_curso        

class Estudiante(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    nombres = models.CharField('Nombres', max_length=20)
    apellidos = models.CharField('Apellidos', max_length=20)
    nombre_completo = models.CharField('Nombre Completo', max_length=40, blank=True)
    
    preguntas = models.ManyToManyField(Preguntas,through='EstudiantePreguntas', blank=True)

    #class Meta:
    #    verbose_name = 'Estudiante'
    #    verbose_name_plural = 'Estudiantes del curso'
    #    ordering = ['-nombres', 'apellidos']

    def __str__(self):
        return self.nombres + ' ' + self.apellidos

class EstudiantePreguntas(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    preguntas = models.ForeignKey(Preguntas, on_delete=models.CASCADE)

    correcto = models.BooleanField()

    def nombresestudiante(self):
        return  self.estudiante.nombres + ' ' + self.estudiante.apellidos

    def __str__(self):
        return self.estudiante.nombres + ' ' + self.estudiante.apellidos + ' ' + self.preguntas.pregunta + ' ' + str(self.correcto)

p2/base/forms.py
from django.forms import ModelForm
from .models import Curso, Estudiante, Prueba, Preguntas, EstudiantePreguntas, Tema

class CursoForm(ModelForm):
    class Meta:
        model = Curso
        fields = '__all__'

class EstudianteForm(ModelForm):
    class Meta:
        model = Estudiante
        fields = ('curso','nombres','apellidos','nombre_completo',)    

class EstudiantePreguntasForm(ModelForm):
    class Meta:
        model = EstudiantePreguntas
        fields = '__all__'        

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['preguntas'].queryset = Preguntas.objects.filter(user=user)    
  

class PruebaForm(ModelForm):
    class Meta:
        model = Prueba
        fields = ('nombre_prueba',)

class PreguntasForm(ModelForm):

    class Meta:
        model = Preguntas
        fields = ('prueba', 'tema', 'pregunta',)

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['prueba'].queryset = Prueba.objects.filter(user=user)    

class UPreguntasForm(ModelForm):

    class Meta:
        model = Preguntas
        fields = ('pregunta',)

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['prueba'].queryset = Prueba.objects.filter(user=user)  

class TemaForm(ModelForm):
    class Meta:
        model = Tema
        fields = '__all__'

p2/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .models import Curso, Estudiante, EstudiantePreguntas, Prueba, Preguntas, Tema
from .forms import CursoForm, EstudianteForm, PruebaForm, PreguntasForm, UPreguntasForm, EstudiantePreguntasForm, TemaForm


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('bienvenida')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'El usuario ingresado no existe')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('bienvenida')
        else:
            messages.error(request, 'El usuario o contraseña no existe')

    context = {'page':page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('bienvenida')

def registerPage(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('bienvenida')
        else:
            messages.error(request, 'Un error ha ocurrido durante el registro')
    return render(request, 'base/login_register.html', {'form': form})

def bienvenida(request):
    return render(request, 'base/bienvenida.html')

@login_required(login_url='login')
def listacursos(request):
    cursos = Curso.objects.all()
    cursos_count = cursos.count()
    context = {'cursos': cursos, 'cursos_count': cursos_count}
    return render(request, 'base/listacursos.html', context)

@login_required(login_url='login')
def crearCurso(request):
    form = CursoForm()
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def actualizarCurso(request, pk):
    curso = Curso.objects.get(id=pk)
    form = CursoForm(instance=curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarCurso(request, pk):
    curso = Curso.objects.get(id=pk)
    if request.method == 'POST':
        curso.delete()
        return redirect('listacursos')
    return render(request, 'base/delete.html', {'obj':curso})

@login_required(login_url='login')
def curso(request, pk):
    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}
    return render(request, 'base/curso.html', context)

@login_required(login_url='login')
def crearEstudiante(request, pk):
    curso = Curso.objects.get(id=pk)
    context = {'curso': curso}
    form = EstudianteForm()
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'base/curso.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def actualizarEstudiante(request, pk):
    estudiante = Estudiante.objects.get(id=pk)
    form = EstudianteForm(instance=estudiante)
    if request.method == 'POST':
        form = EstudianteForm(request.POST, instance=estudiante)
        if form.is_valid():
            form.save()
            return redirect('listacursos')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarEstudiante(request, pk):
    estudiante = Estudiante.objects.get(id=pk)
    if request.method == 'POST':
        estudiante.delete()
        return redirect('listacursos')
    return render(request, 'base/delete.html', {'obj':estudiante})

@login_required(login_url='login')
def listapruebas(request):
    pruebas = Prueba.objects.filter(user=request.user)
    pruebas_count = pruebas.count()
    context = {'pruebas': pruebas, 'pruebas_count':pruebas_count}
    return render(request, 'base/listapruebas.html', context)

@login_required(login_url='login')
def crearPrueba(request):
    form = PruebaForm()
    if request.method == 'POST':
        form = PruebaForm(request.POST)
        if form.is_valid():
            prueba = form.save(commit=False)
            prueba.user = request.user
            prueba.save()
            return redirect('listapruebas')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def actualizarPrueba(request, pk):
    prueba = Prueba.objects.get(id=pk)
    form = PruebaForm(instance=prueba)
    if request.method == 'POST':
        form = PruebaForm(request.POST, instance=prueba)
        if form.is_valid():
            form.save()
            return redirect('listapruebas')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarPrueba(request, pk):
    prueba = Prueba.objects.get(id=pk)
    if request.method == 'POST':
        prueba.delete()
        return redirect('listapruebas')
    return render(request, 'base/delete.html', {'obj':prueba})  

@login_required(login_url='login')
def prueba(request, pk):
    prueba = Prueba.objects.get(id=pk)
    context = {'prueba': prueba}
    return render(request, 'base/prueba.html', context)

@login_required(login_url='login')
def crearPreguntas(request, pk):
    prueba = Prueba.objects.get(id=pk)
    context = {'prueba': prueba}
    form = PreguntasForm(user=request.user)
    if request.method == 'POST':
        form = PreguntasForm(request.POST, user=request.user)
        if form.is_valid():
            pregunta = form.save(commit=False)
            pregunta.user = request.user
            pregunta.save()
            return render(request, 'base/prueba.html', context)
    context = {'form': form}
    return render(request, 'base/curso_form.html', context) 

@login_required(login_url='login')
def actualizarPreguntas(request, pk):
    pregunta = Preguntas.objects.get(id=pk)
    form = UPreguntasForm(instance=pregunta)
    if request.method == 'POST':
        form = UPreguntasForm(request.POST, instance=pregunta)
        if form.is_valid():
            form.save()
            return redirect('listapruebas')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def eliminarPreguntas(request, pk):
    pregunta = Preguntas.objects.get(id=pk)
    if request.method == 'POST':
        pregunta.delete()
        return redirect('listapruebas')
    return render(request, 'base/delete.html', {'obj':pregunta})

@login_required(login_url='login')
def relacionarPreguntas(request, pk):
    a = Preguntas.objects.get(id=pk)
    if request.method == 'POST':
        form = EstudiantePreguntasForm(request.POST, user=request.user)
        if form.is_valid():
            relacion = form.save(commit=False)
            relacion.user = request.user
            relacion.save()
            return redirect('listapruebas')
    else:
        form = EstudiantePreguntasForm(user=request.user)
    return render(request, 'base/curso_form.html', {'form': form, 'a':a})

@login_required(login_url='login')
def pregunta(response, pk):
    a = Preguntas.objects.get(id=pk)

    if response.method == 'POST':
        print(response.POST)
        if response.POST.get('save'):
            for estudiantepreguntas in a.estudiantepreguntas_set.all():
                if response.POST.get('c' + str(estudiantepreguntas.id)) == 'clicked':
                    estudiantepreguntas.correcto = True
                else:
                    estudiantepreguntas.correcto = False

                estudiantepreguntas.save()
                
    return render(response, 'base/pregunta.html', {"a":a})

@login_required(login_url='login')
def eliminarRelacionPreguntas(request, pk):
    b = EstudiantePreguntas.objects.get(id=pk)
    if request.method == 'POST':
        b.delete()
        return redirect('listapruebas')
    return render(request, 'base/delete.html', {'obj':b})

@login_required(login_url='login')
def listatemas(request):
    temas = Tema.objects.all()
    context = {'temas': temas}
    return render(request, 'base/listatemas.html', context)

@login_required(login_url='login')
def crearTema(request):
    form = TemaForm()
    if request.method == 'POST':
        form = TemaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listatemas')
    context = {'form': form}
    return render(request, 'base/curso_form.html', context)

@login_required(login_url='login')
def actualizarTema(request, pk):
    tema = Tema.objects.get(id=pk)
    form = TemaForm(instance=tema)
    if request.method == 'POST':
        form = TemaForm(request.POST, instance=tema)

p2/base/templates/base/bienvenida.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <html>
        <body>
            bienvenidos
        </body>
    </html>
</div>
{% endblock content %}

p2/base/templates/base/curso.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{curso.nombre_curso}}</h1>
<div>
    <a href="{% url 'crear-estudiante' curso.id %}">Añadir estudiante</a>
    <div>
        {% for estudiante in curso.estudiante_set.all %}
            <div>
                <h3>{{estudiante.nombres}} {{estudiante.apellidos}}</h3>
                <a href="{% url 'actualizar-estudiante' estudiante.id %}">Actualizar estudiante</a>   
                <a href="{% url 'eliminar-estudiante' estudiante.id %}">Eliminar estudiante</a>     
            </div>
        {% empty %}
            No existe aún ningún estudiante relacionado al curso.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/curso_form.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</div>

{% endblock content %}

p2/base/templates/base/delete.html
{% extends 'base/main.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p>Estás seguro que quieres eliminar a "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Volver</a>
    <input type="submit" value="Confirmar">
</form>

{% endblock content %}

p2/base/templates/base/estudiantepreguntas1.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{preguntas.pregunta}}</h1>
<div>

    <div>
        {% for pregunta. in preguntas.estudiantepreguntas_set.all %}
            <div>
                <h3>{{estudiantepreguntas.estudiante_id}} {{estudiantepreguntas.correcto}}</h3>
            </div>
        {% empty %}
            No existe aún ninguna pregunta relacionado a la prueba.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/listacursos.html
{% extends 'base/main.html' %}

{% block content %}

<div>
    <h1>Cursos</h1>
    <div>
        <h4>{{cursos_count}} cursos en el grado</h4>
        <a href="{% url 'crear-curso' %}">Crear curso</a>
        <div>
            {% for curso in cursos %}
                <div>
                    <h3><a href="/curso/{{curso.id}}">{{curso.nombre_curso}}</a></h3>
                    <a href="{% url 'actualizar-curso' curso.id %}">Actualizar curso</a>   
                    <a href="{% url 'eliminar-curso' curso.id %}">Eliminar curso</a>           
                    <!-- <h3>{{curso.id}} -- <a href="{% url 'curso' curso.id %}">{{curso.nombre_curso}}</a></h3> -->
                </div>
            {% empty %}
                No existe aún ningún curso añadido.
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

p2/base/templates/base/listapruebas.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Pruebas</h1>
<div>
    <h4>{{pruebas_count}} pruebas añadidas</h4>
    <a href="{% url 'crear-prueba' %}">Añadir prueba</a>
    <div>
        {% for prueba in pruebas.all %}
            <div>
                <h3><a href="/prueba/{{prueba.id}}">{{prueba.nombre_prueba}}</a></h3>
                <a href="{% url 'actualizar-prueba' prueba.id %}">Actualizar prueba</a> 
                <a href="{% url 'eliminar-prueba' prueba.id %}">Eliminar prueba</a>     
            </div>
        {% empty %}
            No existe aún ninguna prueba añadida.
        {% endfor %}
    </div>
</div>
{% endblock content %}

p2/base/templates/base/listatemas.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Temas</h1>
<div>
    <a href="{% url 'crear-tema' %}">Crear tema</a>
    <div>
        {% for tema in temas %}
            <div>
                <h3>{{tema.nombre_tema}}</h3>
                <a href="{% url 'actualizar-tema' tema.id %}">Actualizar tema</a>   
                <a href="{% url 'eliminar-tema' tema.id %}">Eliminar tema</a>           
            </div>
        {% empty %}
            No existe aún ningún tema añadido.
        {% endfor %}
    </div>
</div>

{% endblock content %}

p2/base/templates/base/login_register.html
{% extends 'base/main.html' %}

{% block content %}
{%  if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token %}
        <label>Nombre de usuario:</label>
        <input type="text" name="username" placeholder="Ingresa tu nombre de usuario"/>

        <label>Contraseña:</label>
        <input type="password" name="password" placeholder="Ingresa tu contraseña"/>

        <input type="submit" value="Inicia sesión"/>

    </form>

    <p>No se ha registrado aún?</p>
    <a href="{% url 'register' %}">Regístrate</a>
</div>

{% else %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Regístrate"/>
    </form>
    <p>Ya estás registrado?</p>
    <a href="{% url 'login' %}">Inicia sesión</a>
</div>
{% endif %}
{% endblock %}

p2/base/templates/base/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Analisis de rendimiento</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'> 
</head>
<body>
    {% include 'base/navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    
    {% block content %}

    {% endblock %}
    
</body>
</html>

p2/base/templates/base/navbar.html
<div>
    <div>        
        {% if user.is_authenticated %}
            <h3>Hola profesor {{ user.first_name }}!</h3>
        {% else %}
            <h3>Hola usuario!</h3>
        {% endif %}       
    </div>
    <div>
        <a href="/">Bienvenida</a>
        <a>...</a>
        <a href="{% url 'listacursos' %}">Ver lista de los cursos </a>
        <a>...</a>
        <a href="{% url 'listapruebas' %}">Ver pruebas añadidas</a>
        <a>...</a>
        <a href="{% url 'listatemas' %}">Ver temas añadidos</a>
        <a>...</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Cerrar sesión</a>    
        {% else %}
            <a href="{% url 'login' %}">Iniciar sesión</a>   
        {% endif %}
    </div>
    <hr>
</div>

p2/base/templates/base/pregunta.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Pregunta: {{a.pregunta}}</h1>
<h3>Proviene de prueba: {{a.nombreprueba}} y tema: {{a.nombretema}}</h3>
<a href="{% url 'relacionar-preguntas' a.id %}">Relacionar pregunta</a>
<form method="POST" action="#">
    {% csrf_token %}
    <ul>
        {% for estudiantepreguntas in a.estudiantepreguntas_set.all %}
            {% if estudiantepreguntas.correcto == True %}
                <li><input type="checkbox", value="clicked", name="c{{estudiantepreguntas.id}}" checked>{{estudiantepreguntas.nombresestudiante}} respondió correctamente la pregunta</li>
            {% else %}    
                <li><input type="checkbox", value="clicked", name="c{{estudiantepreguntas.id}}">{{estudiantepreguntas.nombresestudiante}} NO respondió correctamente la pregunta</li>
            {% endif %}
            <a href="{% url 'eliminar-relacion-preguntas' estudiantepreguntas.id %}">Eliminar relación</a>
        {% endfor %}
    </ul>
    <button type="submit", name="save", value="save">Guardar</button>
</form> 
{% endblock content %}

p2/base/templates/base/prueba.html
{% extends 'base/main.html' %}

{% block content %}

<h1>{{prueba.nombre_prueba}}</h1>
<div>
    <a href="{% url 'crear-preguntas' prueba.id %}">Añadir pregunta</a>
    <div>
        {% for preguntas in prueba.preguntas_set.all %}
            <div>
                <h3><a href="/pregunta/{{preguntas.id}}">{{preguntas.pregunta}}</a></h3>

                <a href="{% url 'actualizar-preguntas' preguntas.id %}">Actualizar pregunta</a> 
                <a href="{% url 'eliminar-preguntas' preguntas.id %}">Eliminar pregunta</a>
            </div>
        {% empty %}
            No existe aún ninguna pregunta relacionado a la prueba.
        {% endfor %}
    </div>
</div>
{% endblock content %}